version: "3"
services:
  directus:
    image: directus/directus:10.9.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "veryinsecurekeydonotuse"
      SECRET: "veryinsecurekeydonotuse"
      ADMIN_EMAIL: "admin@amtcm.com"
      ADMIN_PASSWORD: "admind1r3"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true" 
      EXTENSIONS_AUTO_RELOAD: "true"